apiVersion: v1
kind: Service
metadata:
  name: {{ include "pretend-youre-xyzzy.fullname" . }}
  labels:
    {{- include "pretend-youre-xyzzy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pretend-youre-xyzzy.selectorLabels" . | nindent 4 }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
